


--- False pos ---
HAC.SERVER.White_FalsePositives = {
	"KR30=host_framerate gStr(0.00 != 0)",
	"KR30=host_framerate vStr(0.00 != 0)",
	"CVCheck: host_framerate (host_framerate) 0.00 != 0",
	
	"turret_sound [[0]]",
	
	"mod/lua/autorun/cl_anti-cheat.lua",
	"mod/lua/autorun/sv_anti-cheat.lua",
	"mod/data/anti-cheat_logs/anti-cheat.txt",
	"mod/lua/autorun/client/cl_shakeview.lua",
	
	
	"ECheckW=MOD/addons/JBS Robots/lua/autorun/jbs_female_robot_mk2_cvp.lua-3730340338 (bot) - ***SKIP*** (robot)",
	"ECheckW=MOD/addons/JBS Robots/lua/autorun/jbs_fodder_cvp.lua-3012226660 (bot) - ***SKIP*** (robot)",
	"ECheckW=MOD/lua/autorun/client/allhooks_tofixdam_hackygmod.lua-3810014785 (hack) - ***SKIP*** (hacky)",
	"ECheckW=MOD/lua/autorun/include/pill_tf_robots.lua-2773048642 (bot) - ***SKIP*** (robot)",
	"ECheckW=MOD/lua/autorun/npc_stealth_wepsounds.lua-1814711819 (steal) - ***SKIP*** (stealth)",
	"ECheckW=MOD/lua/autorun/stealth_katana_weplist.lua-3652385410 (steal) - ***SKIP*** (stealth)",
	"ECheckW=MOD/lua/autorun/stealth_npc_convars.lua-2577290167 (steal) - ***SKIP*** (stealth)",
	"ECheckW=MOD/lua/autorun/stealthnpcweaponpanel.lua-2978306419 (steal) - ***SKIP*** (stealth)",
	"ECheckW=MOD/lua/autorun/client/cl_haxicons.lua-720409633 (hax) - ***SKIP*** (/cl_haxicons.lua)",
	"ECheckW=MOD/lua/autorun/sh_hax_config.lua-1926498831 (hax) - ***SKIP*** (/sh_hax_config.lua)",
	"ECheckW=MOD/lua/ev_plugins/sh_hax.lua-1789674952 (hax) - ***SKIP*** (/sh_hax.lua)",
	"ECheckW=MOD/lua/ev_plugins/sh_norecoil.lua-1576853925 (recoil) - ***SKIP*** (sh_norecoil)",
	"ECheckW=MOD/lua/autorun/server/botvoodoo.lua-2549161001 (bot) - ***SKIP*** (/botvoodoo.lua)",
	"ECheckW=MOD/lua/cl_hack_check_vgui_type.lua-3312311485 (hack) - ***SKIP*** (/cl_hack_check_vgui_type.lua)",
	"ECheckW=MOD/lua/autorun/cbb_haku_append.lua-1038261722 (hak) - ***SKIP*** (haku)",
	"ECheckW=MOD/lua/autorun/stealthkatanaconvars.lua-2928045005 (steal) - ***SKIP*** (stealth)",
	"ECheckW=MOD/lua/autorun/stealth_katana_weplist.lua-4156499837 (steal) - ***SKIP*** (stealth)",
	"ECheckW=MOD/lua/autorun/include/pill_tf_robots.lua-1993194618 (bot) - ***SKIP*** (robot)",
	"ECheckW=MOD/lua/autorun/sw_oldbots.lua-630974325 (bot) - ***SKIP*** (oldbot)",
	"ECheckW=MOD/lua/autorun/sw_robot_npc_player.lua-2447153425 (bot) - ***SKIP*** (robot)",
	"ECheckW=MOD/lua/autorun/cbb_haku_append.lua-2255873984 (hak) - ***SKIP*** (haku)",
	"ECheckW=MOD/lua/doom/cheats.lua-1816366068 (cheat) - ***SKIP*** (/doom/cheats)",
	"ECheckW=MOD/lua/doom/autoaim.lua-2408310390 (autoaim.lua) - ***SKIP*** (/doom/autoaim)",
	"ECheckW=MOD/lua/autorun/roboteyeglow_particle_mounter.lua-1234036920 (bot) - ***SKIP*** (robot)",
	"ECheckW=MOD/lua/autorun/evilscaryrobotsfromouterspace.lua-3746337464 (bot) - ***SKIP*** (robot)",
	"ECheckW=MOD/lua/autorun/terrorist_bot.lua-245357592 (bot) - ***SKIP*** (/terrorist_bot.lua)",
	"ECheckW=MOD/lua/autorun/terrorist_bot_npc.lua-925603645 (bot) - ***SKIP*** (/terrorist_bot_npc.lua)",
	"ECheckW=MOD/lua/autorun/client/cl_shakeview.lua-1345973317 (hak)",
	"mod/addons/livecontenthack/lua/autorun/contenthack.lua",
	"mod/addons/livecontenthack/lua/autorun/game_ep2.lua",
	"mod/addons/livecontenthack/lua/autorun/game_hl2.lua",
	"ECheckW=MOD/addons/LiveContentHack/lua/autorun/contenthack.lua-2957019124 (hack)",
	"ECheckW=MOD/addons/LiveContentHack/lua/autorun/game_ep2.lua-2252575089 (hack)",
	"ECheckW=MOD/addons/LiveContentHack/lua/autorun/game_hl2.lua-3640962351 (hack)",
	"addons/PAC3/lua/pac3/core/client/parts/shake.lua",
	"ECheckW=addons/PAC3/lua/pac3/core/client/parts/shake.lua",
	"ECheckW=addons/PAC3/lua/pac3/core/client/parts/shake.lua-446195300 (hak)",
	"ECheckW=MOD/lua/autorun/cl_anti-cheat.lua-572380701 (cheat)",
	"ECheckW=MOD/lua/autorun/sv_anti-cheat.lua-2484775306 (cheat)",
	"ECheckW=MOD/data/anti-cheat_logs/anti-cheat.txt-825125234 (cheat)",
	"ECheckW=MOD/lua/autorun/gm_botmap_v3_particle_precache.lua-2297874470 (bot)",
	"ECheckW=MOD/lua/autorun/client/cl_shakeview.lua",
	"HKSW=mod/lua/autorun/gm_botmap_v3_particle_precache.lua-2297874470 (bot)",
	"HKSW=mod/lua/autorun/client/cl_shakeview.lua-1345973317 (hak)",
	"GimmeRX_BAD_RX('lua/sv_loz.lua', 0)",
	"ECheckW=EXECUTABLE_PATH/CSS Content Addon (Dec2013)/scripts/game_sounds_bots.txt-1020088045 (bot)",
	
	
	
	
	"ICheck=NotFO(addons/css_content/materials/particle/old)",
	"ICheck=NotFO(addons/chatsounds/sound/chatsounds/autoadd/arnold)",
	"ICheck=NotFO(addons/chatsounds/sound/chatsounds/autoadd/old)",
	"ICheck=NotFO(addons/HL2+ Content Addon (Jul2014)/materials/particle/old)",
	"ICheck=NotFO(addons/CSS Content Addon (Dec2013)part1/materials/particle/old)",
	"ICheck=NotFO(lua/autorun/halo_4_spartan_sniper_sounds - áíôßãñáöï.lua)",
	"ICheck=NotFO(addons/CSS Content Addon (Jul2014)/materials/particle/old)",
	"ICheck=NotFO(addons/cstrike/materials/particle/old)",
	"ICheck=NotFO(addons/experimentalacf/models/tankgun_old)",
	"ICheck=NotFO(addons/CSS-Content/materials/particle/old)",
	"ICheck=NotFO(addons/CSS Content/materials/particle/old)",
	"ICheck=NotFO(addons/CSS Pour Garry's Mod/CSS content addon/materials/particle/old)",
	"ICheck=NotFO(addons/css/materials/models/weapons/x_models/millenia_bak)",
	"ICheck=NotFO(addons/css/materials/models/weapons/v_models/millenia_bak)",
	"ICheck=NotFO(addons/CSS Content Addon/CSS Content Addon (Dec2013)/materials/particle/old)",
	"ICheck=NotFO(addons/addons/CSS Content Addon/materials/particle/old)",
	"ICheck=NotFO(addons/HL2 & HL2 DM Content Addon/materials/particle/old)",
	"ICheck=NotFO(addons/Game Content Addons/CSS Content Addon (Dec2013)/materials/particle/old)",
	"ICheck=NotFO(addons/HL2_&_HL2_DM_Content_Addon_(Dec2013)/HL2 & HL2 DM Content Addon (Dec2013)/materials/particle/old)",
	"ICheck=NotFO(addons/TDM/data/vcmod_old)",
	"ICheck=NotFO(addons/CSS_Content_Addon_(Dec2013)/CSS Content Addon (Dec2013)/materials/particle/old)",
	"ICheck=NotFO(addons/Crystal dragon/sound/dragon/old)",
	"ICheck=NotFO(addons/dragon_snpc/sound/dragon/old)",
	"ICheck=NotFO(addons/Extra Customizable Weaponry/Sound/Weapons/famf1/old)",
	"ICheck=NotFO(addons/Extra Customizable Weaponry/Sound/Weapons/m98/old)",
	"ICheck=NotFO(addons/CSS Content Addon/CSS Content Addon/materials/particle/old)",
	"ICheck=NotFO(addons/CSS Content Addon (Dec2013)1/materials/particle/old)",
	"ICheck=NotFO(addons/css content/materials/particle/old)",
	"ICheck=NotFO(addons/CSS_Content_2014/materials/particle/old)",
	"ICheck=NotFO(addons/TDM Dealer/data/vcmod_old)",
	"ICheck=NotFO(CSS Content Addon (Dec2013)/materials/particle/old)",
	"ICheck=NotFO(addons/HL2 & HL2 DM Content Addon (Dec2013)/materials/particle/old)",
	"ICheck=NotFO(addons/TF2_Content_Addon_(2014)/materials/backpack/workshop/player/items/all_class/heart_of_gold)",
	"ICheck=NotFO(addons/TF2_Content_Addon_(2014)/materials/models/workshop/player/items/all_class/heart_of_gold)",
	"ICheck=NotFO(addons/TF2_Content_Addon_(2014)/models/workshop/player/items/all_class/heart_of_gold)",
	"ICheck=NotFO(data/autogroup/hold)",
	"ICheck=NotFO(addons/CSS Content Addon (Dec2013)/materials/particle/old)",
	"ICheck=NotFO(addons/Minecraft SWEP/materials/models/mcmodelpack/cloth-old)",
	"ICheck=NotFO(addons/dans_snpcs/lua/entities/npc_facehugger_old)",
	"ICheck=NotFO(addons/dans_snpcs/lua/entities/npc_snork_old)",
	"ICheck=NotFO(addons/dans_snpcs/sound/jihadist/old)",
	"ICheck=NotFO(addons/dans_snpcs/sound/soviet/old)",
	"ICheck=NotFO(addons/CSS - Contenu/materials/particle/old)",
	"ICheck=NotFO(lua/autorun/makarov's_men_npcs.lua)",
	"ICheck=NotFO(lua/autorun/more strider's.lua)",
	"ICheck=NotFO(lua/autorun/skeleton(friendly).lua)",
	"ICheck=NotFO(lua/autorun/skeleton(hostile).lua)",
	"ICheck=NotFO(lua/autorun/skeleton(passive).lua)",
	"ICheck=NotFO(lua/autorun/more strider's.lua)",
	"ICheck=NotFO(addons/particle/old)",
	"ICheck=NotFO(lua/autorun/(dis)connect.lua)",
	"ICheck=NotFO(lua/autorun/rebels_&_overwatch_npc.lua)",
	"ICheck=NotFO(addons/Wireextra/lua/autorun/MHD_gates+chips-1.lua)",
	"ICheck=NotFO(lua/materials/particle/old)",
	"ICheck=NotFO(addons/css_content_for_gmod/materials/particle/old)",
	"ICheck=NotFO(addons/Server_custom_scripts/lua/autorun/server/npc's_item_dropping.lua)",
	"ICheck=NotFO(addons/css/materials/particle/old)",
	"ICheck=NotFO(lua/autorun/metro2033_npcs(largepack).lua)",
	"ICheck=NotFO(addons/Css Models/materials/particle/old)",
	"ICheck=NotFO(addons/CSS - Content/materials/particle/old)",
	"ICheck=NotFO(data/luabee/saved files/compiled lua)",
	"ICheck=NotFO(addons/Extra Customizable Weaponry/lua/autorun/firesnd (2).lua)",
	"ICheck=NotFO(addons/Extra Customizable Weaponry/lua/autorun/client/relsnd (2).lua)",
	"ICheck=NotFO(addons/Extra Customizable Weaponry/lua/autorun/server/cstm_filedl (2).lua)",
	"ICheck=NotFO(addons/NeuroNaval/materials/models/Roller_old)",
	"ICheck=NotFO(addons/Raising The Bar Global Pack/materials/models/Roller_old)",
	"ICheck=NotFO(addons/Raising The Bar Global Pack/materials/models/headcrabold)",
	"ICheck=NotFO(addons/Raising The Bar Global Pack/materials/models/metrold)",
	"ICheck=NotFO(addons/CSS/materials/particle/old)",
	"ICheck=NotFO(lua/autorun/t800's_npcs.lua)",
	"ICheck=NotFO(lua/autorun/smod_tactical_npc's.lua)",
	"ICheck=NotFO(lua/autorun/smod_combine_npc's.lua)",
	"ICheck=NotFO(lua/autorun/skeleton(friendly).lua)",
	"ICheck=NotFO(lua/autorun/skeleton(hostile).lua)",
	"ICheck=NotFO(lua/autorun/skeleton(passive).lua)",
	"ICheck=NotFO(lua/doom/old)",
	"ICheck=NotFO(lua/autorun/fonix_weapon_sounds(5).lua)",
	"ICheck=NotFO(addons/CSS JOA/materials/particle/old)",
	"ICheck=NotFO(addons/materials/particle/old)",
	"ICheck=NotFO(lua/autorun/crysis_npc's.lua)",
	"ICheck=NotFO(lua/autorun/more strider's.lua)",
	"ICheck=NotFO(addons/CSS content addon/materials/particle/old)",
	"ICheck=NotFO(addons/CSS Content Addon/materials/particle/old)", --Ignore this damn thing
	"ICheck=NotFO(data/vcmod_old)",
	"ICheck=NotFO(addons/predcontent/materials/models/weapons/v_models/millenia_bak)",
	
	"ICheck=SizeOf(RP_EvoCity_v4b1.rar) > 194356884",
	
	"ECheckW=MOD/addons/chatsoundsforgmod/lua/chatsounds/lists_send/sfx/bot.lua-3610234784 (bot)",
	"ECheckW=MOD/addons/chatsoundsforgmod/lua/chatsounds/lists_nosend/techbot.lua-2872847627 (bot)",
	"HKSW=lua/cl_hack_check_vgui_type.lua-3037832395 (hack)",
}





